CREATE DATABASE lecturas_libres;
USE lecturas_libres;

CREATE TABLE users(
id_user INT AUTO_INCREMENT PRIMARY KEY,
user_name VARCHAR (255) NOT NULL,
identity INT UNIQUE NOT NULL, 
email VARCHAR (255) UNIQUE NOT NULL,
phone INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);

CREATE TABLE books(
id_book INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR (255) NOT NULL,
isbn VARCHAR (255) UNIQUE NOT NULL,
year_publication DATE NOT NULL,
author VARCHAR (255) NOT NULL
);

CREATE TABLE loans(
id_loan INT AUTO_INCREMENT PRIMARY KEY,
loan_date DATE NOT NULL,
return_date DATE NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
id_user INT,
id_book INT,
FOREIGN KEY (id_user) REFERENCES users(id_user) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (id_book) REFERENCES books(id_book) ON DELETE SET NULL ON UPDATE CASCADE
);