-- Database free_readings
CREATE DATABASE free_readings;
USE free_readings;

-- Users table
CREATE TABLE users(
id_user INT AUTO_INCREMENT PRIMARY KEY,
user_name VARCHAR (255) NOT NULL,
identity INT UNIQUE NOT NULL, 
email VARCHAR (255) UNIQUE NOT NULL,
phone INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);

-- Books table
CREATE TABLE books(
isbn VARCHAR (100) PRIMARY KEY,
title VARCHAR (255) NOT NULL,
year_publication DATE NOT NULL,
author VARCHAR (255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Loans table
CREATE TABLE loans(
id_loan INT AUTO_INCREMENT PRIMARY KEY,
loan_date DATE NOT NULL,
return_date DATE NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
id_user INT,
isbn VARCHAR (100),
FOREIGN KEY (id_user) REFERENCES users(id_user) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (isbn) REFERENCES books(isbn) ON DELETE SET NULL ON UPDATE CASCADE
);